export type TabType = 'ai_solver' | 'motion' | 'force' | 'energy' | 'quiz' | 'unit_converter' | 'cheatsheet';

export interface PhysicsToolDefinition {
  id: string;
  tab: TabType;
  subtopic?: string;
  titleEn: string;
  titleBn: string;
  categoryEn: string;
  categoryBn: string;
  formulaLatex?: string;
  descriptionEn: string;
  descriptionBn: string;
  iconName: 'Activity' | 'Sliders' | 'Zap' | 'Sparkles' | 'ArrowRightLeft' | 'BookOpen' | 'BrainCircuit' | 'Compass' | 'Atom' | 'Gauge';
  badgeEn?: string;
  badgeBn?: string;
  keywords: string[];
}

export interface RecentToolRecord extends PhysicsToolDefinition {
  lastAccessed: number; // Unix timestamp in ms
}

export const PHYSICS_SOLVER_TOOLS: PhysicsToolDefinition[] = [
  {
    id: 'motion_1d',
    tab: 'motion',
    subtopic: '1d',
    titleEn: '1D Linear Motion (SUVAT)',
    titleBn: '১ডি একমাত্রিক গতিবিদ্যা (SUVAT)',
    categoryEn: 'Kinematics',
    categoryBn: 'গতিবিদ্যা',
    formulaLatex: 'v = u + at, \\quad s = ut + \\frac{1}{2}at^2',
    descriptionEn: 'Solve displacement, velocities, acceleration, and travel time under constant acceleration.',
    descriptionBn: 'সুষম ত্বরণে সরণ, আদিবেগ, শেষবেগ, ত্বরণ ও সময় নির্ণয় করুন।',
    iconName: 'Activity',
    badgeEn: 'SUVAT',
    badgeBn: 'সমীকরণ',
    keywords: ['motion', 'kinematics', 'suvat', 'velocity', 'acceleration', 'displacement', '1d', 'গতি', 'সরণ', 'ত্বরণ', 'বেগ'],
  },
  {
    id: 'motion_projectile',
    tab: 'motion',
    subtopic: 'projectile',
    titleEn: '2D Projectile Motion Trajectory',
    titleBn: '২ডি প্রক্ষেপক ও প্রাস গতি (Projectile)',
    categoryEn: 'Kinematics',
    categoryBn: 'গতিবিদ্যা',
    formulaLatex: 'R = \\frac{v_0^2\\sin 2\\theta}{g}, \\quad H = \\frac{v_0^2\\sin^2\\theta}{2g}',
    descriptionEn: 'Calculate projectile apex height, flight time, velocity vectors, and horizontal range.',
    descriptionBn: 'প্রক্ষেপকের সর্বোচ্চ উচ্চতা, বিচরণকাল, বেগ উপাংশ ও অনুভূমিক পাল্লা হিসাব করুন।',
    iconName: 'Compass',
    badgeEn: '2D Arc',
    badgeBn: 'প্রাস',
    keywords: ['projectile', 'trajectory', 'angle', 'launch', 'apex', 'range', 'flight time', 'প্রাস', 'পাল্লা', 'উচ্চতা'],
  },
  {
    id: 'force_flat',
    tab: 'force',
    subtopic: 'flat_friction',
    titleEn: 'Flat Surface Friction & F=ma',
    titleBn: 'সমতল পৃষ্ঠের ঘর্ষণ ও নিউটনের ২য় সূত্র',
    categoryEn: 'Dynamics',
    categoryBn: 'বলবিদ্যা',
    formulaLatex: '\\Sigma F = ma, \\quad f_s \\le \\mu_s N, \\quad f_k = \\mu_k N',
    descriptionEn: 'Calculate pulling force, normal reaction, static/kinetic friction, and acceleration.',
    descriptionBn: 'টান বল, অভিলম্ব প্রতিক্রিয়া, স্থিতি ও চল ঘর্ষণ এবং লব্ধি ত্বরণ নির্ণয় করুন।',
    iconName: 'Sliders',
    badgeEn: 'F = ma',
    badgeBn: 'বল',
    keywords: ['force', 'friction', 'newton', 'mass', 'acceleration', 'normal force', 'ঘর্ষণ', 'বল', 'ত্বরণ', 'ভর'],
  },
  {
    id: 'force_incline',
    tab: 'force',
    subtopic: 'inclined_plane',
    titleEn: 'Inclined Plane Dynamics',
    titleBn: 'আনত তলের গতি ও বল উপাংশ',
    categoryEn: 'Dynamics',
    categoryBn: 'বলবিদ্যা',
    formulaLatex: 'F_\\parallel = mg\\sin\\theta, \\quad N = mg\\cos\\theta',
    descriptionEn: 'Resolve parallel and perpendicular gravity components with slope friction and ramp acceleration.',
    descriptionBn: 'আনত তলে মহাকর্ষ বলের উপাংশ, ঘর্ষণ বল এবং ঢাল বরাবর ত্বরণ বিশ্লেষণ করুন।',
    iconName: 'Atom',
    badgeEn: 'Ramp',
    badgeBn: 'আনত তল',
    keywords: ['incline', 'ramp', 'slope', 'angle', 'gravity components', 'sliding', 'আনত তল', 'ঢাল', 'উপাংশ'],
  },
  {
    id: 'energy_work',
    tab: 'energy',
    subtopic: 'work',
    titleEn: 'Work Done by Constant Force',
    titleBn: 'ধ্রুব বল দ্বারা কৃতকাজ (Work Done)',
    categoryEn: 'Work & Energy',
    categoryBn: 'কাজ ও শক্তি',
    formulaLatex: 'W = \\vec{F} \\cdot \\vec{d} = F d \\cos\\theta',
    descriptionEn: 'Determine scalar work done from force, displacement distance, and vector angle.',
    descriptionBn: 'বল, সরণ ও মধ্যবর্তী কোণের ডট গুণন থেকে মোট কৃতকাজ পরিমাপ করুন।',
    iconName: 'Zap',
    badgeEn: 'Joules',
    badgeBn: 'জুল',
    keywords: ['work', 'force', 'displacement', 'joules', 'dot product', 'কাজ', 'জুল', 'সরণ'],
  },
  {
    id: 'energy_conservation',
    tab: 'energy',
    subtopic: 'conservation',
    titleEn: 'Conservation of Mechanical Energy',
    titleBn: 'যান্ত্রিক শক্তির নিত্যতা সূত্র',
    categoryEn: 'Work & Energy',
    categoryBn: 'কাজ ও শক্তি',
    formulaLatex: 'E_{total} = \\frac{1}{2}mv^2 + mgh = \\text{const}',
    descriptionEn: 'Analyze kinetic and potential energy conversions in free fall, rollercoasters, and slopes.',
    descriptionBn: 'পড়ন্ত বস্তু বা রোলারকোস্টারে গতিশক্তি ও বিভব শক্তির রূপান্তর ও নিত্যতা যাচাই করুন।',
    iconName: 'Zap',
    badgeEn: 'Ek + Ep',
    badgeBn: 'শক্তি',
    keywords: ['energy', 'conservation', 'kinetic', 'potential', 'rollercoaster', 'height', 'গতিশক্তি', 'বিভব শক্তি', 'নিত্যতা'],
  },
  {
    id: 'energy_power',
    tab: 'energy',
    subtopic: 'power',
    titleEn: 'Power & Mechanical Efficiency',
    titleBn: 'ক্ষমতা ও যান্ত্রিক কর্মদক্ষতা',
    categoryEn: 'Power & Work',
    categoryBn: 'ক্ষমতা ও কাজ',
    formulaLatex: 'P = \\frac{W}{t} = F v, \\quad \\eta = \\frac{P_{out}}{P_{in}} \\times 100\\%',
    descriptionEn: 'Compute rate of energy delivery, Watts to horsepower conversions, and percent efficiency.',
    descriptionBn: 'কাজ করার হার, ওয়াট থেকে অশ্বক্ষমতা রূপান্তর এবং শতাংশ কর্মদক্ষতা হিসাব করুন।',
    iconName: 'Gauge',
    badgeEn: 'Watts / HP',
    badgeBn: 'ওয়াট',
    keywords: ['power', 'efficiency', 'watts', 'horsepower', 'engine', 'rate', 'ক্ষমতা', 'ওয়াট', 'কর্মদক্ষতা', 'অশ্বক্ষমতা'],
  },
  {
    id: 'ai_solver',
    tab: 'ai_solver',
    titleEn: 'AI Problem Solver & Socratic Tutor',
    titleBn: 'এআই পদার্থবিজ্ঞান সমাধান ও টিউটর',
    categoryEn: 'AI Tutor',
    categoryBn: 'এআই শিক্ষক',
    formulaLatex: '\\text{Natural Language} \\rightarrow \\text{LaTeX Steps}',
    descriptionEn: 'Type or paste any high school physics word problem for step-by-step mathematical derivation.',
    descriptionBn: 'যেকোনো পদার্থবিজ্ঞান গাণিতিক প্রশ্ন লিখে ধাপে ধাপে গাণিতিক সমাধান ও ব্যাখ্যা পান।',
    iconName: 'Sparkles',
    badgeEn: 'AI Smart',
    badgeBn: 'স্মার্ট এআই',
    keywords: ['ai', 'solver', 'tutor', 'problem', 'natural language', 'word problem', 'এআই', 'সমাধান', 'প্রশ্ন'],
  },
  {
    id: 'quiz_practice',
    tab: 'quiz',
    titleEn: 'Interactive Physics Formula Quiz',
    titleBn: 'পদার্থবিজ্ঞান সূত্র অনুশীলন কুইজ',
    categoryEn: 'Self Test',
    categoryBn: 'অনুশীলন',
    formulaLatex: '\\text{Practice} \\& \\text{Real-time Score}',
    descriptionEn: 'Adaptive multi-difficulty formula challenges with instant step validations and scorecards.',
    descriptionBn: 'তাৎক্ষণিক যাচাই, ইঙ্গিত ও স্কোরবোর্ডসহ পদার্থবিজ্ঞানের সূত্র অনুশীলন করুন।',
    iconName: 'BrainCircuit',
    badgeEn: 'Quiz',
    badgeBn: 'কুইজ',
    keywords: ['quiz', 'test', 'practice', 'questions', 'score', 'formula test', 'কুইজ', 'পরীক্ষা', 'অনুশীলন'],
  },
  {
    id: 'unit_speed',
    tab: 'unit_converter',
    subtopic: 'speed',
    titleEn: 'Speed & Velocity Unit Converter',
    titleBn: 'গতি ও দ্রুতির একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ m/s} = 3.6\\text{ km/h} \\approx 2.237\\text{ mph}',
    descriptionEn: 'Instant conversions between m/s, km/h, mph, knots, and ft/s with dimensional steps.',
    descriptionBn: 'মিটার/সেকেন্ড, কিমি/ঘণ্টা, মাইল/ঘণ্টা এবং নট এককের তাৎক্ষণিক রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'm/s ↔ km/h',
    badgeBn: 'দ্রুতি',
    keywords: ['unit', 'speed', 'velocity', 'converter', 'km/h', 'm/s', 'mph', 'একক', 'গতি', 'রূপান্তর'],
  },
  {
    id: 'unit_force',
    tab: 'unit_converter',
    subtopic: 'force',
    titleEn: 'Force & Weight Unit Converter',
    titleBn: 'বল ও ওজনের একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ N} = 10^5\\text{ dyn} \\approx 0.2248\\text{ lbf}',
    descriptionEn: 'Convert Newtons, dynes, pound-force (lbf), and kilogram-force (kgf).',
    descriptionBn: 'নিউটন, ডাইন, পাউন্ড-বল এবং কিলোগ্রাম-বল এককের নিখুঁত রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'N ↔ lbf',
    badgeBn: 'বল',
    keywords: ['unit', 'force', 'newton', 'dyne', 'lbf', 'kgf', 'একক', 'বল', 'নিউটন'],
  },
  {
    id: 'unit_energy',
    tab: 'unit_converter',
    subtopic: 'energy',
    titleEn: 'Energy & Work Unit Converter',
    titleBn: 'কাজ ও শক্তির একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ J} = 10^7\\text{ erg} \\approx 0.239\\text{ cal}',
    descriptionEn: 'Convert between Joules, Kilojoules, calories, electron-volts (eV), and kilowatt-hours (kWh).',
    descriptionBn: 'জুল, ক্যালোরি, কিলোওয়াট-ঘণ্টা এবং ইলেকট্রন-ভোল্ট এককের মধ্যে রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'J ↔ kWh',
    badgeBn: 'শক্তি',
    keywords: ['unit', 'energy', 'joules', 'calories', 'kwh', 'ev', 'work unit', 'একক', 'জুল', 'ক্যালোরি'],
  },
  {
    id: 'unit_power',
    tab: 'unit_converter',
    subtopic: 'power',
    titleEn: 'Power & Energy Rate Converter',
    titleBn: 'ক্ষমতার একক রূপান্তর (Power)',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ hp} \\approx 745.7\\text{ W} = 0.7457\\text{ kW}',
    descriptionEn: 'Convert mechanical horsepower, Watts, kilowatts, and metric horsepower.',
    descriptionBn: 'মেকানিক্যাল অশ্বক্ষমতা (hp), ওয়াট এবং কিলোওয়াটের পারস্পরিক রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'W ↔ HP',
    badgeBn: 'ক্ষমতা',
    keywords: ['unit', 'power', 'watts', 'horsepower', 'hp', 'kw', 'একক', 'ক্ষমতা', 'ওয়াট'],
  },
  {
    id: 'unit_acceleration',
    tab: 'unit_converter',
    subtopic: 'acceleration',
    titleEn: 'Acceleration Unit Converter',
    titleBn: 'ত্বরণ ও মন্দন একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ g} \\approx 9.80665\\text{ m/s}^2 \\approx 32.174\\text{ ft/s}^2',
    descriptionEn: 'Convert standard gravitational acceleration (g), m/s², and ft/s².',
    descriptionBn: 'মহাকর্ষীয় ত্বরণ (g), m/s² এবং ফুট/বর্গসেকেন্ড এককের রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'm/s² ↔ g',
    badgeBn: 'ত্বরণ',
    keywords: ['unit', 'acceleration', 'gravity', 'g-force', 'm/s2', 'একক', 'ত্বরণ', 'মহাকর্ষ'],
  },
  {
    id: 'unit_pressure',
    tab: 'unit_converter',
    subtopic: 'pressure',
    titleEn: 'Pressure & Stress Unit Converter',
    titleBn: 'চাপ ও পীড়ন একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ atm} = 101325\\text{ Pa} = 760\\text{ mmHg}',
    descriptionEn: 'Convert Pascals (Pa), atmospheres (atm), bar, psi, and mmHg.',
    descriptionBn: 'প্যাসকেল (Pa), বায়ুমণ্ডলীয় চাপ (atm), বার ও টরের রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'Pa ↔ atm',
    badgeBn: 'চাপ',
    keywords: ['unit', 'pressure', 'pascal', 'atm', 'bar', 'psi', 'একক', 'চাপ', 'প্যাসকেল'],
  },
  {
    id: 'unit_length',
    tab: 'unit_converter',
    subtopic: 'length',
    titleEn: 'Length & Distance Unit Converter',
    titleBn: 'দৈর্ঘ্য ও দূরত্বের একক রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ mi} = 1609.34\\text{ m} = 5280\\text{ ft}',
    descriptionEn: 'Convert meters, kilometers, miles, feet, inches, and light years.',
    descriptionBn: 'মিটার, কিলোমিটার, মাইল, ফুট এবং ইঞ্চির সহজ রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'm ↔ mi',
    badgeBn: 'দৈর্ঘ্য',
    keywords: ['unit', 'length', 'distance', 'meters', 'miles', 'feet', 'একক', 'দৈর্ঘ্য', 'দূরত্ব'],
  },
  {
    id: 'unit_mass',
    tab: 'unit_converter',
    subtopic: 'mass',
    titleEn: 'Mass & Weight Converter',
    titleBn: 'ভর ও পদার্থের পরিমাপ রূপান্তর',
    categoryEn: 'Unit Tools',
    categoryBn: 'একক রূপান্তর',
    formulaLatex: '1\\text{ kg} \\approx 2.20462\\text{ lb} = 1000\\text{ g}',
    descriptionEn: 'Convert kilograms, grams, pounds (lb), ounces (oz), and metric tons.',
    descriptionBn: 'কিলোগ্রাম, গ্রাম, পাউন্ড এবং টনের আন্তর্জাতিক একক রূপান্তর।',
    iconName: 'ArrowRightLeft',
    badgeEn: 'kg ↔ lb',
    badgeBn: 'ভর',
    keywords: ['unit', 'mass', 'weight', 'kg', 'grams', 'lbs', 'একক', 'ভর', 'কেজি'],
  },
  {
    id: 'cheatsheet_motion',
    tab: 'cheatsheet',
    subtopic: 'Motion',
    titleEn: 'Kinematics Formula Reference',
    titleBn: 'গতিবিদ্যা সূত্র ভাণ্ডার ও শর্তাবলী',
    categoryEn: 'Reference',
    categoryBn: 'সূত্র ভাণ্ডার',
    formulaLatex: 'v = u + at, \\quad s = ut + \\frac{1}{2}at^2, \\quad v^2 = u^2 + 2as',
    descriptionEn: 'Complete SUVAT equations with condition of applicability and pitfalls.',
    descriptionBn: 'গতির সমীকরণসমূহ, ব্যবহারের শর্ত এবং শিক্ষার্থীদের সাধারণ ভুলসমূহের বিশ্লেষণ।',
    iconName: 'BookOpen',
    badgeEn: 'Formulas',
    badgeBn: 'সূত্র',
    keywords: ['cheatsheet', 'formulas', 'motion', 'kinematics', 'equations', 'সূত্র', 'গতিবিদ্যা'],
  },
  {
    id: 'cheatsheet_force',
    tab: 'cheatsheet',
    subtopic: 'Force',
    titleEn: 'Dynamics & Force Formula Reference',
    titleBn: 'বলবিদ্যা ও নিউটনের সূত্র সহায়িকা',
    categoryEn: 'Reference',
    categoryBn: 'সূত্র ভাণ্ডার',
    formulaLatex: '\\Sigma \\vec{F} = m\\vec{a}, \\quad f_k = \\mu_k N, \\quad F_c = \\frac{mv^2}{r}',
    descriptionEn: "Newton's laws, Coulomb friction formulas, centripetal force equations.",
    descriptionBn: 'নিউটনের গতিসূত্রসমূহ, ঘর্ষণ বলের নিয়মাবলী ও কেন্দ্রমুখী বলের সূত্র।',
    iconName: 'BookOpen',
    badgeEn: 'Formulas',
    badgeBn: 'সূত্র',
    keywords: ['cheatsheet', 'force', 'friction', 'dynamics', 'newton', 'সূত্র', 'বলবিদ্যা'],
  },
  {
    id: 'cheatsheet_energy',
    tab: 'cheatsheet',
    subtopic: 'Work & Energy',
    titleEn: 'Work & Energy Reference Cheat Sheet',
    titleBn: 'কাজ ও শক্তি সূত্র সহায়িকা',
    categoryEn: 'Reference',
    categoryBn: 'সূত্র ভাণ্ডার',
    formulaLatex: 'W = F d\\cos\\theta, \\quad E_k = \\frac{1}{2}mv^2, \\quad E_p = mgh',
    descriptionEn: 'Mechanical work, gravitational potential energy, and conservation formulas.',
    descriptionBn: 'কৃতকাজ, গতিশক্তি, মহাকর্ষীয় বিভব শক্তি ও শক্তির নিত্যতা সূত্রের বিশদ সহায়িকা।',
    iconName: 'BookOpen',
    badgeEn: 'Formulas',
    badgeBn: 'সূত্র',
    keywords: ['cheatsheet', 'work', 'energy', 'kinetic', 'potential', 'conservation', 'সূত্র', 'শক্তি'],
  },
  {
    id: 'cheatsheet_power',
    tab: 'cheatsheet',
    subtopic: 'Power',
    titleEn: 'Power & Efficiency Cheat Sheet',
    titleBn: 'ক্ষমতা ও কর্মদক্ষতা সূত্র সহায়িকা',
    categoryEn: 'Reference',
    categoryBn: 'সূত্র ভাণ্ডার',
    formulaLatex: 'P = \\frac{W}{t} = \\vec{F}\\cdot\\vec{v}, \\quad \\eta = \\frac{P_{out}}{P_{in}} \\times 100\\%',
    descriptionEn: 'Instantaneous and average power equations and efficiency calculations.',
    descriptionBn: 'গড় ক্ষমতা, তাৎক্ষণিক ক্ষমতা ও যান্ত্রিক কর্মদক্ষতা সূত্রের সহায়িকা।',
    iconName: 'BookOpen',
    badgeEn: 'Formulas',
    badgeBn: 'সূত্র',
    keywords: ['cheatsheet', 'power', 'efficiency', 'rate', 'horsepower', 'সূত্র', 'ক্ষমতা'],
  },
];

// Helper to look up a tool by ID
export function getPhysicsToolById(id: string): PhysicsToolDefinition | undefined {
  return PHYSICS_SOLVER_TOOLS.find((t) => t.id === id);
}

// Helper to find a tool by tab and subtopic
export function findToolByTabAndSubtopic(tab: TabType, subtopic?: string): PhysicsToolDefinition | undefined {
  if (subtopic) {
    const match = PHYSICS_SOLVER_TOOLS.find((t) => t.tab === tab && t.subtopic === subtopic);
    if (match) return match;
  }
  return PHYSICS_SOLVER_TOOLS.find((t) => t.tab === tab);
}
