import { PresetProblem } from '../types';

export const PRESET_PROBLEMS: PresetProblem[] = [
  {
    id: 'kinematics_car_brake',
    category: 'motion',
    subtopic: '1D Kinematics & Stopping Distance',
    subtopicBn: 'একমাত্রিক গতি ও ব্রেকিং দূরত্ব',
    difficulty: 'Foundation',
    title: 'Car Braking Distance',
    titleBn: 'গাড়ির ব্রেকিং দূরত্ব ও সময়',
    problemText: 'A car traveling at 25 m/s (approx 90 km/h) slams on its brakes with a constant deceleration of 5.0 m/s². How far does the car travel before coming to a complete stop, and how long does it take to stop?',
    problemTextBn: '২৫ মি/সে (প্রায় ৯০ কিমি/ঘণ্টা) বেগে চলমান একটি গাড়ি ৫.০ মি/সে² সুষম মন্দনে ব্রেক কষে। গাড়িটি সম্পূর্ণ থেমে যাওয়ার পূর্বে কত দূরত্ব অতিক্রম করবে এবং থামতে কত সময় লাগবে?',
    tags: ['Deceleration', 'Stopping Distance', 'SUVAT'],
    tagsBn: ['মন্দন', 'ব্রেকিং দূরত্ব', 'গতির সমীকরণ'],
  },
  {
    id: 'kinematics_cliff_throw',
    category: 'motion',
    subtopic: 'Vertical Free Fall',
    subtopicBn: 'খাড়া নিক্ষেপ ও মুক্ত পতন',
    difficulty: 'Standard',
    title: 'Ball Thrown from a 45m Cliff',
    titleBn: '৪৫ মিটার উঁচু খাড়া পাহাড় থেকে পাথর নিক্ষেপ',
    problemText: 'A stone is thrown vertically upward from the edge of a 45-meter-high cliff with an initial velocity of 20 m/s. Taking g = 9.8 m/s², calculate the maximum height reached above the cliff, the total time before hitting the ground below, and the impact velocity.',
    problemTextBn: 'একটি ৪৫ মিটার উঁচু পাহাড়ের চূড়া থেকে একটি পাথর ২০ মি/সে আদিবেগে খাড়া উপরের দিকে নিক্ষেপ করা হলো। g = ৯.৮ মি/সে² ধরে পাথরটি পাহাড়ের চূড়া থেকে সর্বোচ্চ কত উচ্চতায় উঠবে, ভূমিতে পড়ার মোট সময় এবং ভূমিতে আঘাতের বেগ নির্ণয় করো।',
    tags: ['Free Fall', 'Quadratic Time', 'Gravity'],
    tagsBn: ['মুক্ত পতন', 'সর্বোচ্চ উচ্চতা', 'অভিকর্ষজ ত্বরণ'],
  },
  {
    id: 'projectile_cannon_angle',
    category: 'motion',
    subtopic: '2D Projectile Motion',
    subtopicBn: 'দ্বিমাত্রিক প্রক্ষেপক গতি (Projectile)',
    difficulty: 'Standard',
    title: 'Soccer Ball Kick at 35°',
    titleBn: '৩৫° কোণে ফুটবল কিক',
    problemText: 'A player kicks a soccer ball with an initial speed of 22 m/s at an angle of 35° above the horizontal. Find the maximum height reached by the ball, its total time of flight, and the horizontal distance (range) it travels before hitting the pitch.',
    problemTextBn: 'একজন খেলোয়াড় অনুভূমিকের সাথে ৩৫° কোণে ২২ মি/সে বেগে একটি ফুটবল কিক করলেন। বলটির সর্বাধিক অর্জিত উচ্চতা, মোট উড্ডয়নকাল এবং অনুভূমিক পাল্লা (Range) নির্ণয় করো।',
    tags: ['Trajectory', 'Range', 'Apex Height'],
    tagsBn: ['প্রক্ষেপক', 'পাল্লা', 'উড্ডয়নকাল'],
  },
  {
    id: 'force_crate_friction_angle',
    category: 'force',
    subtopic: "Newton's 2nd Law & Angled Pull",
    subtopicBn: 'নিউটনের ২য় সূত্র ও কোণে প্রযুক্ত বল',
    difficulty: 'Standard',
    title: 'Pulling a Heavy Crate at 30°',
    titleBn: '৩০° কোণে ভারী বাক্স টানা',
    problemText: 'A worker pulls a 40 kg wooden crate across a concrete floor by pulling on a rope with a force of 180 N at an angle of 30° above the horizontal. The coefficient of kinetic friction between the crate and the floor is μk = 0.25. (Use g = 9.8 m/s²). Calculate the normal force, the friction force, and the resulting acceleration of the crate.',
    problemTextBn: 'একজন শ্রমিক অনুভূমিকের সাথে ৩০° কোণে ১৮০ N বল দ্বারা দড়িতে টান দিয়ে ৪০ কেজি ভরের একটি কাঠের বাক্স মেঝে দিয়ে টানছেন। মেঝে ও বাক্সের মধ্যবর্তী চল ঘর্ষণ গুণাঙ্ক μk = ০.২৫ এবং g = ৯.৮ মি/সে² হলে তলের অভিলম্বিক প্রতিক্রিয়া বল, ঘর্ষণ বল এবং বাক্সের ত্বরণ নির্ণয় করো।',
    tags: ['Normal Force Reduction', 'Friction', 'FBD'],
    tagsBn: ['অভিলম্বিক বল', 'ঘর্ষণ বল', 'মুক্ত বস্তু চিত্র'],
  },
  {
    id: 'force_inclined_ramp',
    category: 'force',
    subtopic: 'Inclined Plane Dynamics',
    subtopicBn: 'আনত তলের গতিবিদ্যা',
    difficulty: 'Advanced AP',
    title: 'Block Sliding Down 28° Ramp with Friction',
    titleBn: '২৮° কোণে আনত তলে ঘর্ষণসহ বস্তুর পতন',
    problemText: 'A 15 kg package is placed on a loading ramp inclined at 28° to the horizontal. The coefficient of kinetic friction is 0.18. If the ramp is 6.0 meters long and the package is released from rest, find the acceleration of the package down the ramp and its final speed at the bottom.',
    problemTextBn: 'অনুভূমিকের সাথে ২৮° কোণে আনত একটি ৬.০ মিটার দীর্ঘ তলের শীর্ষ থেকে ১৫ কেজি ভরের একটি বাক্স স্থির অবস্থা থেকে ছেড়ে দেওয়া হলো। চল ঘর্ষণ গুণাঙ্ক ০.১৮ হলে তলের সমান্তরালে বাক্সের ত্বরণ এবং তলের পাদদেশে পৌঁছানোর বেগ নির্ণয় করো।',
    tags: ['Inclined Plane', 'Component Resolution', 'Work-Energy Hybrid'],
    tagsBn: ['আনত তল', 'উপাংশ বিভাজন', 'তলের ত্বরণ'],
  },
  {
    id: 'energy_rollercoaster_loop',
    category: 'work_energy',
    subtopic: 'Conservation of Mechanical Energy',
    subtopicBn: 'যান্ত্রিক শক্তির নিত্যতা সূত্র',
    difficulty: 'Standard',
    title: 'Rollercoaster Drop & Loop-the-Loop',
    titleBn: 'রোলারকোস্টারের পতন ও লুপ গতি',
    problemText: 'A 500 kg roller coaster cart starts from rest at the top of a hill of height h1 = 35 meters. Assuming track friction is negligible (g = 9.8 m/s²), calculate the speed of the cart at the bottom of the drop (h = 0 m) and at the top of a loop of height h2 = 20 meters.',
    problemTextBn: '৫০০ কেজি ভরের একটি রোলারকোস্টার ৩৫ মিটার উচ্চতার একটি পাহাড়ের চূড়া থেকে স্থির অবস্থা হতে চলা শুরু করল। ঘর্ষণ বল উপেক্ষণীয় (g = ৯.৮ মি/সে²) হলে পাহাড়ের পাদদেশে (h = ০ মি) এবং ২০ মিটার উঁচু লুপের শীর্ষবিন্দুতে কোস্টারটির বেগ নির্ণয় করো।',
    tags: ['Energy Conservation', 'Potential Energy', 'Speed at Height'],
    tagsBn: ['শক্তির নিত্যতা', 'গতিশক্তি', 'বিভব শক্তি'],
  },
  {
    id: 'work_elevator_motor',
    category: 'work_energy',
    subtopic: 'Work, Power & Motor Efficiency',
    subtopicBn: 'কাজ, ক্ষমতা ও ইঞ্জিনের কর্মদক্ষতা',
    difficulty: 'Standard',
    title: 'Elevator Lift Power & Efficiency',
    titleBn: 'লিফটের মোটরের ক্ষমতা ও কর্মদক্ষতা',
    problemText: 'An electric elevator motor lifts a loaded cab of total mass 1200 kg vertically upwards by 25 meters in 15 seconds at constant speed. (Take g = 9.8 m/s²). Calculate the minimum work done by the cable, the useful mechanical power delivered by the motor, and the required electrical input power if the motor is 80% efficient.',
    problemTextBn: 'একটি বৈদ্যুতিক লিফট মোটর ১২০০ কেজি ভরের একটি লিফটকে সমবেগে ১৫ সেকেন্ডে ২৫ মিটার উপরে তোলে (g = ৯.৮ মি/সে²)। লিফট উত্তোলনে তার দ্বারা কৃতকাজ, মোটরের কার্যকর যান্ত্রিক ক্ষমতা এবং কর্মদক্ষতা ৮০% হলে প্রয়োজনীয় সরবরাহকৃত বৈদ্যুতিক ক্ষমতা নির্ণয় করো।',
    tags: ['Power', 'Efficiency', 'Watts to HP'],
    tagsBn: ['ক্ষমতা', 'কর্মদক্ষতা', 'ওয়াট ও অশ্বক্ষমতা'],
  },
  {
    id: 'energy_spring_cannon',
    category: 'work_energy',
    subtopic: 'Elastic & Gravitational Potential Energy',
    subtopicBn: 'স্থিতিস্থাপক ও মহাকর্ষীয় বিভব শক্তি',
    difficulty: 'Advanced AP',
    title: 'Vertical Spring Launcher',
    titleBn: 'উল্লম্ব স্প্রিং প্রক্ষেপক',
    problemText: 'A vertical toy cannon uses a spring with spring constant k = 800 N/m compressed by 0.15 m to launch a 0.20 kg ball vertically into the air. Assuming no air resistance and g = 9.8 m/s², calculate the launch speed as it leaves the uncompressed spring and the maximum vertical height reached above the compressed starting position.',
    problemTextBn: 'একটি স্প্রিং বন্দুকের স্প্রিং ধ্রুবক k = ৮০০ N/m। এটিকে ০.১৫ মি সংকুচিত করে ০.২০ কেজি ভরের একটি বলকে খাড়া উপরের দিকে ছোঁড়া হলো। বায়ুর বাধা অগ্রাহ্য করে এবং g = ৯.৮ মি/সে² ধরে স্প্রিং প্রসারণের মুহূর্তে বলটির বেগ এবং সংকুচিত অবস্থান থেকে বলটির অর্জিত সর্বোচ্চ উচ্চতা নির্ণয় করো।',
    tags: ['Hookes Law', 'Elastic PE', 'Total Energy'],
    tagsBn: ['হুকের সূত্র', 'স্প্রিং শক্তি', 'সর্বোচ্চ উচ্চতা'],
  },
];
